<main>
    <h2>Accueil</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae similique consequuntur sed dolor ut quod sit cumque nesciunt aspernatur dignissimos praesentium, enim inventore iste ad hic minima beatae. Rerum, laboriosam?
    Ea dolore mollitia assumenda corporis, accusamus saepe nisi ipsa expedita iste hic, odio minima, maxime veritatis! Odio repellendus molestias incidunt, voluptatibus, dignissimos consectetur earum ipsa, mollitia ipsum ad temporibus recusandae.
    Modi error veniam dicta dolores illo voluptates explicabo labore tempore beatae quidem? Consequuntur totam harum atque quis sequi dolorem sunt, neque excepturi rem quo eveniet ea illo architecto quae distinctio.</p>
</main>