<main>
    <form action="" method="post">
        <div class="row">
            <p class="form-group">
                <label for="email">Email</label>
                <input class="form-control" type="email" name="email" id="email" required>
            </p>

            <p class="form-group ml-4">
                <label for="password">Mot de passe</label>
                <input class="form-control" type="password" name="password" id="password" required>
            </p>

        </div>
        <button type="submit" class="btn btn-secondary">Se connecter</button>
    </form>
</main>